workflows:
  ios-free:
    name: iOS Build Free Apple ID
    environment:
      xcode: 15.0
      cocoapods: default
    scripts:
      - name: Build SwiftUI + SceneKit app
        script: |
          mkdir -p build

          # Archiveを作成
          xcodebuild archive \
            xcodebuild -scheme minecraft_scenekit \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/minecraft_swiftUI.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

          # IPAを生成
          swift build -c release -Xswift -target \
            -archivePath build/minecraft_swiftUI.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ipa
    artifacts:
      - build/ipa/app.ipa
