workflows:
  ios-swiftpm:
    name: Build SwiftPM iOS SceneKit App
    environment:
      xcode: 15.0
      vars:
        APP_NAME: "minecraft_swiftUI"

    scripts:
      - name: Clean previous build
        script: |
          rm -rf .build build DerivedData

      - name: Build using SwiftPM
        script: |
          swift package clean
          swift build -c release

      - name: Archive app
        script: |
          xcodebuild archive \
            -scheme "${APP_NAME}" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "build/${APP_NAME}.xcarchive" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -skipPackagePluginValidation

      - name: Export IPA
        script: |
          mkdir -p build/ipa
          cat > ExportOptions.plist <<EOF
          {
            "method": "ad-hoc",
            "compileBitcode": false,
            "destination": "export",
            "signingStyle": "manual",
            "stripSwiftSymbols": true,
            "thinning": "<none>"
          }
          EOF
          xcodebuild -exportArchive \
            -archivePath "build/${APP_NAME}.xcarchive" \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath "build/ipa" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

    artifacts:
      - build/ipa/*.ipa
      - build/**/*.xcarchive
