workflows:
  ios-ipa:
    name: iOS IPA Build
    environment:
      xcode: 15.0
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.astro.mine_scenekit
    scripts:
      - name: Build IPA
        script: |
          xcodebuild -scheme MySceneKitApp \
          -sdk iphoneos \
          -configuration Release \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          build

          mkdir -p build/ipa
          xcrun -sdk iphoneos PackageApplication \
            -v build/Release-iphoneos/MySceneKitApp.app \
            -o $PWD/build/ipa/MySceneKitApp.ipa
    artifacts:
      - build/ipa/game.ipa
