workflows:
  ios-swiftpm-xcodeproj:
    name: Build SwiftPM iOS App (Temp XcodeProj)
    environment:
      xcode: 15.0
      vars:
        APP_NAME: "minecraft_swiftUI"

    scripts:
      - name: Clean previous build
        script: |
          echo "ðŸ§¹ Cleaning previous build..."
          rm -rf .build build DerivedData *.xcodeproj
          echo "âœ… Clean complete."

      - name: Resolve Swift Package dependencies
        script: |
          echo "ðŸ“¦ Resolving Swift Package dependencies..."
          swift package update
          swift package resolve
          echo "âœ… Dependencies resolved."

      - name: Generate temporary Xcode project
        script: |
          echo "ðŸ› ï¸ Generating temporary Xcode project from SwiftPM..."
          swift package generate-xcodeproj
          echo "âœ… Xcode project generated."

      - name: Archive iOS app (no code signing)
        script: |
          echo "ðŸš€ Archiving iOS app..."
          xcodebuild \
            -project "${APP_NAME}.xcodeproj" \
            -scheme "${APP_NAME}" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "build/${APP_NAME}.xcarchive" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            clean archive

      - name: Export IPA
        script: |
          echo "ðŸ“¦ Exporting IPA..."
          mkdir -p build/ipa
          cat > ExportOptions.plist <<EOF
          {
            "method": "ad-hoc",
            "compileBitcode": false,
            "destination": "export",
            "signingStyle": "manual",
            "stripSwiftSymbols": true,
            "thinning": "<none>"
          }
          EOF
          xcodebuild -exportArchive \
            -archivePath "build/${APP_NAME}.xcarchive" \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath "build/ipa" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

    artifacts:
      - build/ipa/*.ipa
      - build/**/*.xcarchive
