workflows:
  ios-free:
    name: iOS Build Free Apple ID
    environment:
      xcode: 15.0
      os: macos
      flutter: none
      cocoapods: default
    scripts:
      - name: Build SwiftUI + SceneKit app
        script: |
          # ビルド用ディレクトリ作成
          mkdir -p build
          
          # Xcodebuildで署名スキップ
          xcodebuild -scheme minecraft_swiftUI \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build \
            -derivedDataPath build
          
          # IPA生成
          mkdir -p build/ipa
          xcrun -sdk iphoneos PackageApplication \
            -v build/Build/Products/Release-iphoneos/MySceneKitApp.app \
            -o $PWD/build/ipa/MySceneKitApp.ipa
    artifacts:
      - build/ipa/MySceneKitApp.ipa
