workflows:
  build_ios_swiftui:
    name: Build iOS SwiftUI app
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install XcodeGen
        script: brew install xcodegen
      - name: Generate Xcode project
        script: xcodegen generate --spec project.yml
      - name: Build & Archive
        script: |
          xcodebuild -project minecraft_swiftUI.xcodeproj \
                     -scheme minecraft_swiftUI \
                     -sdk iphoneos \
                     -configuration Release \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO \
                     -archivePath build/minecraft_swiftUI.xcarchive \
                     archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath build/minecraft_swiftUI.xcarchive \
                     -exportPath build/ipa \
                     -exportOptionsPlist ExportOptions.plist
artifacts:
  - build/ipa/app.ipa
