name: minecraft_swiftUI
options:
  bundleIdPrefix: com.astro.minecraft-swiftUI
targets:
  minecraft_swiftUI:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: [Sources]
    settings:
      base:
        SWIFT_VERSION: 5.9
